package com.novel.splitter.infrastructure.persistence.mapper;

import com.novel.splitter.domain.enums.EmbedStatus;
import com.novel.splitter.domain.model.Scene;
import com.novel.splitter.domain.model.SceneMetadata;
import com.novel.splitter.infrastructure.persistence.entity.JpaSceneEntity;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.JsonProcessingException;
import org.springframework.stereotype.Component;

@Component
public class SceneMapper {
    private final ObjectMapper objectMapper = new ObjectMapper()
            .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

    public Scene toDomain(JpaSceneEntity entity) {
        if (entity == null) return null;
        SceneMetadata meta = jsonToMetadata(entity.getMetadataJson());
        if (meta == null) {
            meta = new SceneMetadata();
        }
        if (entity.getChunkSize() != null) {
            meta.setChunkSize(entity.getChunkSize());
        }
        if (entity.getChunkOverlap() != null) {
            meta.setChunkOverlap(entity.getChunkOverlap());
        }
        if (entity.getVersion() != null) {
            meta.setVersion(entity.getVersion());
        }
        if (entity.getNovel() != null
                && (meta.getNovel() == null || meta.getNovel().isBlank())) {
            meta.setNovel(entity.getNovel().getId());
        }
        return Scene.builder()
                .persistenceId(entity.getId())
                .id(entity.getSceneId())
                .chapterTitle(entity.getChapterTitle())
                .chapterIndex(entity.getChapterIndex())
                .startParagraphIndex(entity.getStartParagraphIndex())
                .endParagraphIndex(entity.getEndParagraphIndex())
                .text(entity.getText())
                .wordCount(entity.getWordCount())
                .prefixContext(entity.getPrefixContext())
                .canSplit(entity.isCanSplit())
                .seq(entity.getSeq())
                .metadata(meta)
                .score(null)
                .embedStatus(entity.getEmbedStatus())
                .embedError(entity.getEmbedError())
                .embedRunId(entity.getEmbedRunId())
                .build();
    }

    public JpaSceneEntity toEntity(Scene domain) {
        if (domain == null) return null;
        JpaSceneEntity entity = new JpaSceneEntity();
        // DB autogenerated ID (entity.id) intentionally not set here.
        entity.setSceneId(domain.getId());
        entity.setChapterTitle(domain.getChapterTitle());
        entity.setChapterIndex(domain.getChapterIndex());
        entity.setStartParagraphIndex(domain.getStartParagraphIndex());
        entity.setEndParagraphIndex(domain.getEndParagraphIndex());
        entity.setText(domain.getText());
        entity.setWordCount(domain.getWordCount());
        entity.setPrefixContext(domain.getPrefixContext());
        entity.setCanSplit(domain.isCanSplit());
        entity.setMetadataJson(metadataToJson(domain.getMetadata()));
        if (domain.getMetadata() != null) {
            if (domain.getMetadata().getChunkSize() != null) {
                entity.setChunkSize(domain.getMetadata().getChunkSize());
            }
            if (domain.getMetadata().getChunkOverlap() != null) {
                entity.setChunkOverlap(domain.getMetadata().getChunkOverlap());
            }
        }
        entity.setEmbedStatus(domain.getEmbedStatus());
        entity.setEmbedError(domain.getEmbedError());
        entity.setEmbedRunId(domain.getEmbedRunId());
        entity.setSeq(domain.getSeq());
        // novel/chapter/version/isDeleted/legacyNovelName are handled by repository layer.
        return entity;
    }

    public SceneMetadata jsonToMetadata(String json) {
        if (json == null || json.isEmpty()) return null;
        try {
            return objectMapper.readValue(json, SceneMetadata.class);
        } catch (JsonProcessingException e) {
            return null;
        }
    }

    public String metadataToJson(SceneMetadata metadata) {
        if (metadata == null) return null;
        try {
            return objectMapper.writeValueAsString(metadata);
        } catch (JsonProcessingException e) {
            return null;
        }
    }
}