package com.novel.splitter.infrastructure.persistence.mapper;

import com.novel.splitter.domain.model.Scene;
import com.novel.splitter.domain.model.SceneMetadata;
import com.novel.splitter.infrastructure.persistence.entity.JpaSceneEntity;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Named;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.JsonProcessingException;

@Mapper(componentModel = "spring")
public interface SceneMapper {
    ObjectMapper objectMapper = new ObjectMapper();

    @Mapping(target = "id", source = "sceneId")
    @Mapping(target = "metadata", source = "metadataJson", qualifiedByName = "jsonToMetadata")
    @Mapping(target = "score", ignore = true)
    Scene toDomain(JpaSceneEntity entity);

    @Mapping(target = "sceneId", source = "id")
    @Mapping(target = "metadataJson", source = "metadata", qualifiedByName = "metadataToJson")
    @Mapping(target = "id", ignore = true) // DB autogenerated ID
    @Mapping(target = "novel", ignore = true)
    @Mapping(target = "chapter", ignore = true)
    @Mapping(target = "isDeleted", ignore = true)
    @Mapping(target = "novelName", ignore = true)
    @Mapping(target = "version", ignore = true)
    JpaSceneEntity toEntity(Scene domain);

    @Named("jsonToMetadata")
    default SceneMetadata jsonToMetadata(String json) {
        if (json == null || json.isEmpty()) return null;
        try {
            return objectMapper.readValue(json, SceneMetadata.class);
        } catch (JsonProcessingException e) {
            return null;
        }
    }

    @Named("metadataToJson")
    default String metadataToJson(SceneMetadata metadata) {
        if (metadata == null) return null;
        try {
            return objectMapper.writeValueAsString(metadata);
        } catch (JsonProcessingException e) {
            return null;
        }
    }
}